# Default workflow: index genome FASTAs (gunzip + samtools + GATK + BWA).
# Run from repo root:
#   snakemake -s workflow/Snakefile --directory workflow --cores 4 -p --use-conda

import re
from pathlib import Path


configfile: "../config/config.yaml"
include: "rules/common.smk"


SRC = Path(config["source_dir"])
LOG = f"{SRC}/Trep_ref_indexing_logs"
ROWS = load_samples(config["samples_csv"])
ROW_BY_ID = {r["row_id"]: r for r in ROWS}
GENOMES = [r for r in ROWS if r["file_type"] == "genome"]
ASM = lambda r: Path(r["file"].replace(".gz", "")).stem
GENOME_LOOKUP = {(r["source"], ASM(r)): r for r in GENOMES}
SOURCES = [r["source"] for r in GENOMES]
ASSEMBLIES = [ASM(r) for r in GENOMES]
SOURCE_SET = sorted(set(SOURCES))
ASSEMBLY_SET = sorted(set(ASSEMBLIES))


def genome_row(wc):
    return GENOME_LOOKUP[(wc.source, wc.assembly)]


def raw_path(r):
    return str(SRC / r["source"] / r["file"])


wildcard_constraints:
    source="|".join(re.escape(s) for s in SOURCE_SET),
    assembly="|".join(re.escape(a) for a in ASSEMBLY_SET),


rule all:
    input:
        f"{SRC}/Trep_ref_indexing.done",


rule decompress_genome:
    input:
        lambda wc: raw_path(genome_row(wc)),
    output:
        ref=f"{SRC}/{{source}}/{{assembly}}.fna",
    log:
        f"{LOG}/decompress_genome/{{source}}_{{assembly}}.log",
    shell:
        "mkdir -p $(dirname {output.ref}) && gzip -dc {input} > {output.ref} 2> {log}"


rule samtools_faidx:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.fna.fai",
    log:
        f"{LOG}/samtools_faidx/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "samtools faidx {input.ref} 2> {log}"


rule gatk_sequence_dictionary:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.dict",
    log:
        f"{LOG}/gatk_sequence_dictionary/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "gatk CreateSequenceDictionary -R {input.ref} -O {output} 2> {log}"


rule bwa_index:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        multiext(
            f"{SRC}/{{source}}/{{assembly}}.fna",
            ".amb",
            ".ann",
            ".bwt",
            ".pac",
        ),
    log:
        f"{LOG}/bwa_index/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "bwa index {input.ref} 2> {log}"


rule Trep_ref_indexing_done:
    input:
        expand(rules.samtools_faidx.output, zip, source=SOURCES, assembly=ASSEMBLIES),
        expand(rules.gatk_sequence_dictionary.output, zip, source=SOURCES, assembly=ASSEMBLIES),
        expand(rules.bwa_index.output, zip, source=SOURCES, assembly=ASSEMBLIES),
    output:
        f"{SRC}/Trep_ref_indexing.done",
    shell:
        "touch {output}"
